ProyectoBase/Controllers/IMSSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;

namespace ProyectoBase.Controllers
{
    public class IMSSController : Controller
    {
        Models.Usuarios Usuario = (Models.Usuarios)System.Web.HttpContext.Current.Session["Sesion"];
        // GET: IMSS
        public ActionResult Index(Application.Menu menu)
        {
            string url = System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            string cadena = System.Web.HttpContext.Current.Request.Url.AbsolutePath;

            if (menu.ValidacionPagina(Usuario, url))
            {
                Session["LstArchivosIMSS"] = null;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login", new { @rd = Application.UrlCifrardo.Encrypt(cadena), @rdv = Application.UrlCifrardo.Encrypt(url) });
            }
        }

        public ActionResult Descarga(Application.Menu menu, Application.Cat_Cuatrimestre APcat_Cuatrimestre, Application.ArchivoQuincena AParchivoQuincena)
        {
            string url = System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            string cadena = System.Web.HttpContext.Current.Request.Url.AbsolutePath;

            if (menu.ValidacionPagina(Usuario, url))
            {
                List<Models.Cat_Cuatrimestre> cat_Cuatrimestres = APcat_Cuatrimestre.Cat_Cuatrimestre_Seleccionar();
                List<Models.ArchivoQuincena> archivoQuincenas = AParchivoQuincena.ArchivoQuincena_Consultar_Years();
                ViewBag.cat_Cuatrimestres = cat_Cuatrimestres;
                ViewBag.Quincenas = archivoQuincenas;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login", new { @rd = Application.UrlCifrardo.Encrypt(cadena), @rdv = Application.UrlCifrardo.Encrypt(url) });
            }
        }

        [HttpPost]
        public JsonResult IMSS_Archivo_Agregar(List<Models.ArchivoQuincena> archivoQuincenas, Application.Cat_Quincena APcat_Quincena, Application.ArchivoQuincena AParchivoQuincena)
        {
            List<Models.ArchivoQuincena> LstArchivoQuincena = new List<Models.ArchivoQuincena>();

            if (Session["LstArchivosIMSS"] != null)
            {
                LstArchivoQuincena = (List<Models.ArchivoQuincena>)Session["LstArchivosIMSS"];
            }

            char delimitador = ' ';
            foreach (var Quincena in archivoQuincenas)
            {
                Models.ArchivoQuincena archivoQuincena = new Models.ArchivoQuincena();
                Models.Cat_Quincena cat_Quincena = new Models.Cat_Quincena();

                string _Nombre = Quincena.NmOriginal.Remove((Quincena.NmOriginal.Length-4),4);

                string[] valores = _Nombre.Split(delimitador);

                cat_Quincena.Nombre = valores[3];
                cat_Quincena.Mes = valores[4];

                archivoQuincena.Cat_Quincena = APcat_Quincena.Cat_Quincena_Selecionar_Quincena(cat_Quincena);
                archivoQuincena.Year = Convert.ToInt32(valores[5]);
                archivoQuincena.NmArchivo = Quincena.NmArchivo;
                archivoQuincena.NmOriginal = Quincena.NmOriginal;
                archivoQuincena.Resgistro = AParchivoQuincena.ArchivoQuincena_Consultar(archivoQuincena).Resgistro;


                LstArchivoQuincena.Add(archivoQuincena);
            }

            LstArchivoQuincena.Sort((x, y) => string.Compare(x.NmOriginal, y.NmOriginal));
            Session["LstArchivosIMSS"] = LstArchivoQuincena;
            return Json(LstArchivoQuincena);
        }

        [HttpPost]
        public JsonResult IMSS_Archivo_Eliminar(Models.ArchivoQuincena archivoQuincena)
        {
            List<Models.ArchivoQuincena> LstArchivoQuincena = new List<Models.ArchivoQuincena>();

            if (Session["LstArchivosIMSS"] != null)
            {
                LstArchivoQuincena = (List<Models.ArchivoQuincena>)Session["LstArchivosIMSS"];
            }
            LstArchivoQuincena.Remove(LstArchivoQuincena[archivoQuincena.Id]);

            LstArchivoQuincena.Sort((x, y) => string.Compare(x.NmOriginal, y.NmOriginal));
            Session["LstArchivosIMSS"] = LstArchivoQuincena;
            return Json(LstArchivoQuincena);
        }

        [HttpPost]
        public JsonResult IMSS_Archivo_Registrar(Application.ArchivoQuincena AParchivoQuincena)
        {
            bool rsult = false;
            List<Models.ArchivoQuincena> LstArchivoQuincena = new List<Models.ArchivoQuincena>();
            string DirectorioUsuario = System.Web.HttpContext.Current.Request.Url.Authority  + "\\DocumentosIMSS\\";

            if (Session["LstArchivosIMSS"] != null)
            {
                LstArchivoQuincena = (List<Models.ArchivoQuincena>)Session["LstArchivosIMSS"];
            }

            if(LstArchivoQuincena.Count > 0)
            {
                rsult = true;
                // Lectura e inserccion a base de datos.
                foreach (var Quincena in LstArchivoQuincena)
                {
                    if(!Quincena.Resgistro)
                    {
                        Quincena.Usuarios = Usuario;
                        AParchivoQuincena.ArchivoQuincena_Cargatxt(Quincena);
                    }
                }
            }

            return Json(rsult);
        }

        public ActionResult IMSS_Generar_Reporte(Application.ArchivoQuincena AParchivoQuincena)
        {
            int IdCuatrimestre = 0;
            int Year = 0;
            IdCuatrimestre = Convert.ToInt32(Request.QueryString["IdCuatrimestre"].ToString());
            Year = Convert.ToInt32(Request.QueryString["Year"].ToString());

            Models.ArchivoQuincena archivoQuincena = new Models.ArchivoQuincena();
            archivoQuincena.Year = Year;
            Models.Cat_Cuatrimestre cat_Cuatrimestre = new Models.Cat_Cuatrimestre();
            cat_Cuatrimestre.Id = IdCuatrimestre;
            cat_Cuatrimestre.ArchivoQuincena = archivoQuincena;

            DataTable reporte = AParchivoQuincena.ArchivoQuincena_GeneraReporte(cat_Cuatrimestre);

            string date = DateTime.UtcNow.ToString("dd-MM-yyyy");
            //DataSet ds = new DataSet();
            //ds.Tables.Add(dt);

            using (XLWorkbook workbook = new XLWorkbook())
            {
                reporte.TableName = "Empleados";/*Giving table name is mandatory and it must be unique between multiple worksheets*/
                workbook.Worksheets.Add(reporte);
                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename=Reporte IMSS -" + date + ".xlsx");
                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    workbook.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                }

            }

            Response.Flush();
            Response.End();
            return View();
            
        }


        [HttpPost]
        public JsonResult IMSS_Generar_Archivo(Models.Cat_Cuatrimestre cat_Cuatrimestre, Application.ArchivoQuincena AParchivoQuincena)
        {
            DataTable reporte = AParchivoQuincena.ArchivoQuincena_GeneraReporte(cat_Cuatrimestre);

            string date = DateTime.UtcNow.ToString("dd-MM-yyyy");
            //DataSet ds = new DataSet();
            //ds.Tables.Add(dt);

            using (XLWorkbook workbook = new XLWorkbook())
            {
                reporte.TableName = "Empleados";/*Giving table name is mandatory and it must be unique between multiple worksheets*/
                workbook.Worksheets.Add(reporte);
                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename=Reporte IMSS -" + date + ".xlsx");
                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    workbook.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                }

            }

            Response.Flush();
            Response.End();


            return Json("");
        }

    }
}

ProyectoBase/Views/IMSS/Descarga.cshtml
@{
    ViewBag.Title = "Descarga";
    Layout = "~/Views/Shared/_Layout _Administracion.cshtml";
}


<style>

    select.form-control, select.form-control:focus, select.form-control:hover {
        border-top: 1px;
        border-right: 1px;
        border-left: 1px;
        border: 1px solid #cccccc;
        border-radius: 2px;
    }

        select.form-control:not([size]):not([multiple]) {
            height: 36px;
        }

    .alert-warning {
        background-color: #fff;
        border-color: #e91e63;
        color: #fff;
        background: linear-gradient(to right, #e36c95, #e91e63);
        -webkit-box-shadow: 10px 10px 19px -11px rgba(51,51,51,1);
        -moz-box-shadow: 10px 10px 19px -11px rgba(51,51,51,1);
        box-shadow: 10px 10px 19px -11px rgba(51,51,51,1);
    }

    .sweet-mostrar {
        background: linear-gradient(to right, #b02750, #e91e63);
        color: #ffffff;
    }

        .sweet-mostrar:not([disabled]):hover {
            background-color: #e91e63;
            /*#hover here*/
        }

    .sweet-continuar {
        background: linear-gradient(to right, #00bcd4, #036fc5);
        color: #ffffff;
    }

        .sweet-continuar:not([disabled]):hover {
            background-color: #c755db;
            /*#hover here*/
        }

    .modal {
        z-index: 9999;
    }

    .process-step .btn:focus {
        outline: none
    }

    .process {
        display: table;
        width: 100%;
        position: relative
    }

    .process-row {
        display: table-row
    }

    .process-step button[disabled] {
        opacity: 1 !important;
        filter: alpha(opacity=100) !important
    }

    .process-row:before {
        top: 40px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 10px;
        background-color: #ccc;
        z-order: 0;
        border-radius: 5px;
    }

    .process-step {
        display: table-cell;
        text-align: center;
        position: relative
    }

        .process-step p {
            margin-top: 4px
        }

    .btn-uppload {
        background-color: #448aff;
        border-color: #008cb9;
        color: #0083b4;
        cursor: pointer;
        -webkit-transition: all ease-in 0.3s;
        transition: all ease-in 0.3s;
        background: linear-gradient(to right, #ffffff, #ffffff);
        width: 60px;
        border-radius: 5px;
    }

        .btn-uppload:hover {
            background-color: #448aff;
            border-color: #b7b7b7;
            color: #ffffff;
            cursor: pointer;
            -webkit-transition: all ease-in 0.3s;
            transition: all ease-in 0.3s;
            background: linear-gradient(to right, #b9b9b9, #cdcbcb);
        }

    .btn-uppload2 {
        background-color: #448aff;
        border-color: #008cb9;
        color: #0083b4;
        cursor: pointer;
        -webkit-transition: all ease-in 0.3s;
        transition: all ease-in 0.3s;
        background: linear-gradient(to right, #ffffff, #ffffff);
        border-radius: 5px;
    }

        .btn-uppload2:hover {
            background-color: #448aff;
            border-color: #b7b7b7;
            color: #ffffff;
            cursor: pointer;
            -webkit-transition: all ease-in 0.3s;
            transition: all ease-in 0.3s;
            background: linear-gradient(to right, #b9b9b9, #cdcbcb);
        }


    .btn-save {
        border-color: #519f55;
        color: #4caf50;
        cursor: pointer;
        transition: all ease-in 0.3s;
        background: linear-gradient(to right, #efffdc, #dfffba);
    }

        .btn-save:hover {
            border-color: #8bc34a;
            color: #ffffff;
            cursor: pointer;
            transition: all ease-in 0.3s;
            background: linear-gradient(to right, #8bc34a, #8bc34a);
        }

    .btn-danger {
        background: linear-gradient(to right, #9f1c1c, #e91e63);
        /* background-color: #ff5252; */
        border-color: #e91e63;
        color: #fff;
        cursor: pointer;
        -webkit-transition: all ease-in 0.3s;
        transition: all ease-in 0.3s;
        width: 60px;
        border-radius: 5px;
    }

        .btn-danger:hover {
            border-color: #c1c1c1;
            color: #cfbaba;
            cursor: pointer;
            -webkit-transition: all ease-in 0.3s;
            transition: all ease-in 0.3s;
            background: linear-gradient(to right, #a11041, #a50038);
        }

    .btn-view {
        background: linear-gradient(to right, #fff7d5, #fff1c6);
        /* background-color: #ff5252; */
        border-color: #ffc107;
        color: #ff9800;
        cursor: pointer;
        -webkit-transition: all ease-in 0.3s;
        transition: all ease-in 0.3s;
        width: 60px;
        border-radius: 5px;
    }

        .btn-view:hover {
            border-color: #ffeb3b;
            color: #ffffff;
            cursor: pointer;
            -webkit-transition: all ease-in 0.3s;
            transition: all ease-in 0.3s;
            background: linear-gradient(to right, #ff9800, #ff9800);
        }

    .btn-success {
        border-color: #ffffff;
        color: #fff;
        cursor: pointer;
        -webkit-transition: all ease-in 0.3s;
        transition: all ease-in 0.3s;
        background: linear-gradient(to right, #11c15b, #4caf50);
        width: 60px;
        border-radius: 5px;
    }
</style>

<!-- Modal -->
<div class="modal fade" id="CargandoProcesos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cargando ... </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 col-lg-12">
                        <progress id="fileProgress4" style="width:100%"></progress>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="BtnCerrarCargandoProcesos"> Cerrar</button>
            </div>
        </div>
    </div>
</div>

<div class="main-body">
    <div class="page-wrapper">
        <!-- Page-body start -->
        <div class="page-body">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Descrga de archivos quincenales IMSS </h5>
                            <span></span>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4 col-lg-4">
                                    <div class="form-group">
                                        <label for="largeInput">* Cuatrimestre  </label>
                                        <select class="form-control" id="Select_Cuatrimestre" onchange="ValidaSelect('Select_Cuatrimestre')">
                                            <option value="0">SELECCIONAR </option>
                                            @foreach (var item1 in ViewBag.cat_Cuatrimestres)
                                            {
                                                <option value="@item1.Id">@item1.Nombre.ToUpper()</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4 col-lg-4">
                                    <div class="form-group">
                                        <label for="largeInput">* Año  </label>
                                        <select class="form-control" id="Select_year" onchange="ValidaSelect('Select_year')">
                                            <option value="0">SELECCIONAR </option>
                                            @foreach (var item1 in ViewBag.Quincenas)
                                            {
                                                <option value="@item1.Year">@item1.Year</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 col-lg-4">
                                    <button class="btn waves-effect waves-light btn-primary col-md-12 " id="BtnGeneraExcel" onclick="BtnGeneraExcel()">  Generar Excel <i class="fa fa-cloud-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/assets/js/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

<script>
    function BtnGeneraExcel() {
        if (ValidarFormulario()) {

            var ArchivoQuincena = new Object();
            ArchivoQuincena.Year = $("#Select_year option:selected").val();

            var Cat_Cuatrimestre = new Object();
            Cat_Cuatrimestre.Id = $("#Select_Cuatrimestre option:selected").val();
            Cat_Cuatrimestre.ArchivoQuincena = ArchivoQuincena;

            window.location.href = '@Url.Action("IMSS_Generar_Reporte", "IMSS")?IdCuatrimestre=' + Cat_Cuatrimestre.Id + '&Year='+ ArchivoQuincena.Year;

            @*$.ajax({
                type: "POST",
                url: "@Url.Action("IMSS_Generar_Archivo", "IMSS")",
                data: JSON.stringify(Cat_Cuatrimestre),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (respuesta) {
                    console.log(respuesta);
                },
                error: errores
            });*@


        } else {
            $.notify({
                icon: 'fa fa-paw',
                message: "Debes completar el formulario:.",
            }, {
                type: 'warning',
                allow_dismiss: false,
                animate: {
                    enter: 'animated rollIn',
                    exit: 'animated rollOut'
                }
            });
        }
    }

    function ValidarFormulario() {
        var result = false;
        $('#Select_Cuatrimestre').css("border", "1px solid #f44336");
        $('#Select_year').css("border", "1px solid #f44336");

        if ($("#Select_Cuatrimestre option:selected").val() > 0) {
            $('#Select_Cuatrimestre').css("border", "1px solid #cccccc");
        }

        if ($("#Select_year option:selected").val() > 0) {
            $('#Select_year').css("border", "1px solid #cccccc");
        }


        if ($("#Select_Cuatrimestre option:selected").val() > 0) {
            if ($("#Select_year option:selected").val() > 0) {
                result = true;
            }
        }
        return result;
    }

    function errores(data) {
        swal({
            title: "UPS",
            text: 'Se ha presentado un problema #18595',

            type: "warning",
            button: "Aceptar",
        });
    }

</script>

<script>
    function ValidaSelect(name) {
        if ($('#' + name + ' option:selected').val() > 0) {
            $('#' + name).css("border", "1px solid #cccccc");
        } else {
            $('#' + name).css("border", "1px solid #f44336");
        }
    }

    $('#IdMenuIMSS').addClass("active pcoded-trigger");
    $('#IdSubMenuDescarga').addClass("active");
</script>

ProyectoBase/Views/IMSS/Download.cshtml
@{
    ViewBag.Title = "Download";
    Layout = "~/Views/Shared/_Layout _Administracion.cshtml";
}

<h2>Download</h2>