ProyectoBase/Controllers/ExpedienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoBase.Controllers
{
    public class ExpedienteController : Controller
    {
        Models.Usuarios Usuario = (Models.Usuarios)System.Web.HttpContext.Current.Session["Sesion"];
        // GET: Expediente
        public ActionResult Index(Application.Menu menu)
        {
            string url = System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            string cadena = System.Web.HttpContext.Current.Request.Url.AbsolutePath;

            if (menu.ValidacionPagina(Usuario, url))
            {

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login", new { @rd = Application.UrlCifrardo.Encrypt(cadena), @rdv = Application.UrlCifrardo.Encrypt(url) });
            }
        }


        public ActionResult FormatoEmail(Application.Menu menu)
        {
            string url = System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            string cadena = System.Web.HttpContext.Current.Request.Url.AbsolutePath;

            if (menu.ValidacionPagina(Usuario, url))
            {

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login", new { @rd = Application.UrlCifrardo.Encrypt(cadena), @rdv = Application.UrlCifrardo.Encrypt(url) });
            }
        }
    }
}

ProyectoBase/Views/Expediente/FormatoEmail.cshtml
@{
    ViewBag.Title = "FormatoEmail";
    Layout = "~/Views/Shared/_Layout _Administracion.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- Page-body start -->
        <div class="page-body">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Formato correo electrónico expediente </h5>
                            <span>Envió de email al concluir expediente al 100%. Completa los campos marcados *  </span>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-2 col-lg-2">
                                    <button class="btn waves-effect waves-light btn-save col-md-12" onclick="window.location='@Url.Action("Index", "Expediente")'" data-toggle="tooltip" data-placement="top" title="" data-original-title="Volver"> <i class="fa fa-arrow-left"></i> Volver   </button>
                                    <br /><br />
                                </div>
                                <div class="col-md-2 col-lg-2">
                                    <button class="btn waves-effect waves-light btn-primary col-md-12" data-toggle="tooltip" data-placement="top" title="" data-original-title="Vista previa"> <i class="fa fa-file"></i> Vista previa  </button>
                                    <br /><br />
                                </div>
                                <div class="col-md-12 col-lg-12">
                                    <div class="row">
                                        <div class="col-md-12 col-lg-12">
                                            <div class="form-group">
                                                <label for="largeInput">* Titulo </label>
                                                <input type="text" class="form-control" id="Formato_Titulo" onchange="ValidaInput('Formato_Titulo')" onkeyup="mayus(this);">
                                            </div>
                                        </div>
                                        <div class="col-md-12 col-lg-12">
                                            <div class="form-group">
                                                <label for="largeInput">* Encabezado  </label>
                                                <input type="text" class="form-control" id="Formato_Encabezado" onchange="ValidaInput('Formato_Encabezado')" onkeyup="mayus(this);">
                                            </div>
                                        </div>
                                        <div class="col-md-12 col-lg-12">
                                            <div class="form-group">
                                                <label for="largeInput"> Mensaje   </label>
                                                <textarea class="form-control" id="Observaciones_Mensaje" required="" rows="6" onkeyup="mayus(this);"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2 col-lg-2">
                                    <button class="btn waves-effect waves-light btn-primary col-md-12" data-toggle="tooltip" data-placement="top" title="" data-original-title="Guardar captura"> <i class="fa fa-save"></i> Guardar </button>
                                    <br /><br />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/assets/js/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script>

    function mayus(e) {
        e.value = e.value.toUpperCase();
    }


    $('#IdMenuConfiguracion').addClass("active pcoded-trigger");
    $('#IdSubMenuCorreos').addClass("active pcoded-trigger");
    $('#IdCorreosAccesoExpediente').addClass("active");
</script>

ProyectoBase/Views/Expediente/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout _Administracion.cshtml";
}

<div class="main-body">
    <div class="page-wrapper">
        <!-- Page-body start -->
        <div class="page-body">
            <div class="row">
                <div class="col-xl-12 col-md-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Correo electrónico expediente </h5>
                            <span>Envió de email al concluir expediente al 100%. Completa los campos marcados *  </span>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-10 col-lg-10">
                                   
                                </div>
                                <div class="col-md-2 col-lg-2">
                                    <button class="btn waves-effect waves-light btn-primary col-md-12" onclick="window.location='@Url.Action("FormatoEmail", "Expediente")'" data-toggle="tooltip" data-placement="top" title="" data-original-title="Modificar formato email"> <i class="fa fa-envelope"></i> Formato email </button>
                                    <br /><br />
                                </div>
                                <div class="col-md-12 col-lg-12">
                                    <strong><span>Lista de empleados autorizados </span></strong>
                                    <br /><br />
                                </div>
                                <div class="col-md-12 col-lg-12">
                                    
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/assets/js/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script>
   
    $('#IdMenuConfiguracion').addClass("active pcoded-trigger");
    $('#IdSubMenuCorreos').addClass("active pcoded-trigger");
    $('#IdCorreosAccesoExpediente').addClass("active");
</script>